# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-DirWatch-Object
version:      0.01
version_from: lib/POE/Component/DirWatch/Object.pm
installdirs:  site
requires:
    Moose:                         0.05
    POE:                           0.12
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
